@echo off
echo Connecting to phone...
C:\adb\adb.exe connect 192.168.1.3:5555
echo Clearing cache...
C:\adb\adb.exe shell pm clear com.android.gl2jni
echo Uninstalling apk...
C:\adb\adb.exe uninstall com.android.gl2jni
echo Installing apk...
C:\adb\adb.exe install C:\Users\niels\Downloads\app-release.apk
echo Launching apk...
C:\adb\adb.exe shell am start -n com.android.gl2jni/.GL2JNIActivity